In [202]:
import numpy as np

data1 = [1,2,3,4,5]
data1


[1, 2, 3, 4, 5]

In [203]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [204]:
# numpy를 이용하여 array 정의하기
# 1. 위에서 만든 python list를 이용
arr1 = np.array(data1)
arr1


array([1, 2, 3, 4, 5])

In [205]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [206]:
# 2. 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [207]:
arr2.shape

(5,)

In [208]:
# array의 자료형을 확인할 수 있다.
arr2.dtype

dtype('int32')

In [209]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [210]:
arr3.shape

(5,)

In [211]:
arr3.dtype

dtype('float64')

In [212]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [213]:
arr4.shape

(4, 3)

In [214]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [215]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [216]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [217]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [218]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [220]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1


array([[1, 2, 3],
       [4, 5, 6]])

In [221]:
arr1.shape

(2, 3)

In [222]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2


array([[10, 11, 12],
       [13, 14, 15]])

In [223]:
arr2.shape

(2, 3)

In [224]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [225]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [226]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [227]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [228]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [229]:
arr1.shape

(2, 3)

In [230]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [231]:
arr3.shape

(3,)

In [232]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [233]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [234]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [235]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [236]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
# 0번째 요소
arr1[0]

0

In [238]:
# 3번째 요소
arr1[3]

3

In [239]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [240]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [241]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [242]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[0,0]

1

In [253]:
# 2행의 모든 요소 꺼내기
arr2[1,1:]

array([6, 7, 8])

In [244]:
# 2행의 3번째 요소 꺼내기
arr2[2,3]

12

In [245]:
# 모든 행의 3번째 요소 꺼내기
arr2[:,3]

array([ 4,  8, 12])

In [255]:
arr2>7

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [256]:
arr2[arr2>7]

array([ 8,  9, 10, 11, 12])